# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: outbox/v1/account.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import outbox.v1.account_pb2 as outbox_dot_v1_dot_account__pb2


class AccountService(Protocol):
    async def create_account(self, request: outbox_dot_v1_dot_account__pb2.CreateAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.CreateAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_account(self, request: outbox_dot_v1_dot_account__pb2.GetAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.GetAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_accounts(self, request: outbox_dot_v1_dot_account__pb2.ListAccountsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.ListAccountsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_account(self, request: outbox_dot_v1_dot_account__pb2.UpdateAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.UpdateAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def claim_account(self, request: outbox_dot_v1_dot_account__pb2.ClaimAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.ClaimAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_account(self, request: outbox_dot_v1_dot_account__pb2.DeleteAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.DeleteAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def resolve_account(self, request: outbox_dot_v1_dot_account__pb2.ResolveAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.ResolveAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AccountServiceASGIApplication(ConnectASGIApplication[AccountService]):
    def __init__(self, service: AccountService | AsyncGenerator[AccountService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/outbox.v1.AccountService/CreateAccount": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.CreateAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.CreateAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_account,
                ),
                "/outbox.v1.AccountService/GetAccount": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.GetAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.GetAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_account,
                ),
                "/outbox.v1.AccountService/ListAccounts": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAccounts",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.ListAccountsRequest,
                        output=outbox_dot_v1_dot_account__pb2.ListAccountsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_accounts,
                ),
                "/outbox.v1.AccountService/UpdateAccount": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.UpdateAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.UpdateAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_account,
                ),
                "/outbox.v1.AccountService/ClaimAccount": Endpoint.unary(
                    method=MethodInfo(
                        name="ClaimAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.ClaimAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.ClaimAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.claim_account,
                ),
                "/outbox.v1.AccountService/DeleteAccount": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.DeleteAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.DeleteAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_account,
                ),
                "/outbox.v1.AccountService/ResolveAccount": Endpoint.unary(
                    method=MethodInfo(
                        name="ResolveAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.ResolveAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.ResolveAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.resolve_account,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.AccountService"


class AccountServiceClient(ConnectClient):
    async def create_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.CreateAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.CreateAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.CreateAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.CreateAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.GetAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.GetAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.GetAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.GetAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_accounts(
        self,
        request: outbox_dot_v1_dot_account__pb2.ListAccountsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.ListAccountsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAccounts",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.ListAccountsRequest,
                output=outbox_dot_v1_dot_account__pb2.ListAccountsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.UpdateAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.UpdateAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.UpdateAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.UpdateAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def claim_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.ClaimAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.ClaimAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ClaimAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.ClaimAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.ClaimAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.DeleteAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.DeleteAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.DeleteAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.DeleteAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def resolve_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.ResolveAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.ResolveAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.ResolveAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.ResolveAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AccountServiceSync(Protocol):
    def create_account(self, request: outbox_dot_v1_dot_account__pb2.CreateAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.CreateAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_account(self, request: outbox_dot_v1_dot_account__pb2.GetAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.GetAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_accounts(self, request: outbox_dot_v1_dot_account__pb2.ListAccountsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.ListAccountsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_account(self, request: outbox_dot_v1_dot_account__pb2.UpdateAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.UpdateAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def claim_account(self, request: outbox_dot_v1_dot_account__pb2.ClaimAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.ClaimAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_account(self, request: outbox_dot_v1_dot_account__pb2.DeleteAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.DeleteAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def resolve_account(self, request: outbox_dot_v1_dot_account__pb2.ResolveAccountRequest, ctx: RequestContext) -> outbox_dot_v1_dot_account__pb2.ResolveAccountResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AccountServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AccountServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/outbox.v1.AccountService/CreateAccount": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.CreateAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.CreateAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_account,
                ),
                "/outbox.v1.AccountService/GetAccount": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.GetAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.GetAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_account,
                ),
                "/outbox.v1.AccountService/ListAccounts": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAccounts",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.ListAccountsRequest,
                        output=outbox_dot_v1_dot_account__pb2.ListAccountsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_accounts,
                ),
                "/outbox.v1.AccountService/UpdateAccount": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.UpdateAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.UpdateAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_account,
                ),
                "/outbox.v1.AccountService/ClaimAccount": EndpointSync.unary(
                    method=MethodInfo(
                        name="ClaimAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.ClaimAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.ClaimAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.claim_account,
                ),
                "/outbox.v1.AccountService/DeleteAccount": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.DeleteAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.DeleteAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_account,
                ),
                "/outbox.v1.AccountService/ResolveAccount": EndpointSync.unary(
                    method=MethodInfo(
                        name="ResolveAccount",
                        service_name="outbox.v1.AccountService",
                        input=outbox_dot_v1_dot_account__pb2.ResolveAccountRequest,
                        output=outbox_dot_v1_dot_account__pb2.ResolveAccountResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.resolve_account,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.AccountService"


class AccountServiceClientSync(ConnectClientSync):
    def create_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.CreateAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.CreateAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.CreateAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.CreateAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.GetAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.GetAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.GetAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.GetAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_accounts(
        self,
        request: outbox_dot_v1_dot_account__pb2.ListAccountsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.ListAccountsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAccounts",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.ListAccountsRequest,
                output=outbox_dot_v1_dot_account__pb2.ListAccountsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.UpdateAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.UpdateAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.UpdateAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.UpdateAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def claim_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.ClaimAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.ClaimAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ClaimAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.ClaimAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.ClaimAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.DeleteAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.DeleteAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.DeleteAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.DeleteAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def resolve_account(
        self,
        request: outbox_dot_v1_dot_account__pb2.ResolveAccountRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_account__pb2.ResolveAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveAccount",
                service_name="outbox.v1.AccountService",
                input=outbox_dot_v1_dot_account__pb2.ResolveAccountRequest,
                output=outbox_dot_v1_dot_account__pb2.ResolveAccountResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
