# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: outbox/v1/channel.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import outbox.v1.channel_pb2 as outbox_dot_v1_dot_channel__pb2


class ChannelService(Protocol):
    async def get_channel(self, request: outbox_dot_v1_dot_channel__pb2.GetChannelRequest, ctx: RequestContext) -> outbox_dot_v1_dot_channel__pb2.GetChannelResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_channels(self, request: outbox_dot_v1_dot_channel__pb2.ListChannelsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_channel__pb2.ListChannelsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ChannelServiceASGIApplication(ConnectASGIApplication[ChannelService]):
    def __init__(self, service: ChannelService | AsyncGenerator[ChannelService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/outbox.v1.ChannelService/GetChannel": Endpoint.unary(
                    method=MethodInfo(
                        name="GetChannel",
                        service_name="outbox.v1.ChannelService",
                        input=outbox_dot_v1_dot_channel__pb2.GetChannelRequest,
                        output=outbox_dot_v1_dot_channel__pb2.GetChannelResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_channel,
                ),
                "/outbox.v1.ChannelService/ListChannels": Endpoint.unary(
                    method=MethodInfo(
                        name="ListChannels",
                        service_name="outbox.v1.ChannelService",
                        input=outbox_dot_v1_dot_channel__pb2.ListChannelsRequest,
                        output=outbox_dot_v1_dot_channel__pb2.ListChannelsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_channels,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.ChannelService"


class ChannelServiceClient(ConnectClient):
    async def get_channel(
        self,
        request: outbox_dot_v1_dot_channel__pb2.GetChannelRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_channel__pb2.GetChannelResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetChannel",
                service_name="outbox.v1.ChannelService",
                input=outbox_dot_v1_dot_channel__pb2.GetChannelRequest,
                output=outbox_dot_v1_dot_channel__pb2.GetChannelResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_channels(
        self,
        request: outbox_dot_v1_dot_channel__pb2.ListChannelsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_channel__pb2.ListChannelsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListChannels",
                service_name="outbox.v1.ChannelService",
                input=outbox_dot_v1_dot_channel__pb2.ListChannelsRequest,
                output=outbox_dot_v1_dot_channel__pb2.ListChannelsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ChannelServiceSync(Protocol):
    def get_channel(self, request: outbox_dot_v1_dot_channel__pb2.GetChannelRequest, ctx: RequestContext) -> outbox_dot_v1_dot_channel__pb2.GetChannelResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_channels(self, request: outbox_dot_v1_dot_channel__pb2.ListChannelsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_channel__pb2.ListChannelsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ChannelServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ChannelServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/outbox.v1.ChannelService/GetChannel": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetChannel",
                        service_name="outbox.v1.ChannelService",
                        input=outbox_dot_v1_dot_channel__pb2.GetChannelRequest,
                        output=outbox_dot_v1_dot_channel__pb2.GetChannelResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_channel,
                ),
                "/outbox.v1.ChannelService/ListChannels": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListChannels",
                        service_name="outbox.v1.ChannelService",
                        input=outbox_dot_v1_dot_channel__pb2.ListChannelsRequest,
                        output=outbox_dot_v1_dot_channel__pb2.ListChannelsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_channels,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.ChannelService"


class ChannelServiceClientSync(ConnectClientSync):
    def get_channel(
        self,
        request: outbox_dot_v1_dot_channel__pb2.GetChannelRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_channel__pb2.GetChannelResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetChannel",
                service_name="outbox.v1.ChannelService",
                input=outbox_dot_v1_dot_channel__pb2.GetChannelRequest,
                output=outbox_dot_v1_dot_channel__pb2.GetChannelResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_channels(
        self,
        request: outbox_dot_v1_dot_channel__pb2.ListChannelsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_channel__pb2.ListChannelsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListChannels",
                service_name="outbox.v1.ChannelService",
                input=outbox_dot_v1_dot_channel__pb2.ListChannelsRequest,
                output=outbox_dot_v1_dot_channel__pb2.ListChannelsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
