# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: outbox/v1/connector.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.longrunning.operations_pb2 as google_dot_longrunning_dot_operations__pb2
import outbox.v1.connector_pb2 as outbox_dot_v1_dot_connector__pb2


class ConnectorService(Protocol):
    async def create_connector(self, request: outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_managed_connector(self, request: outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_connector(self, request: outbox_dot_v1_dot_connector__pb2.GetConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.GetConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_connectors(self, request: outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_connector(self, request: outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_connector(self, request: outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def detach_provisioned_resource(self, request: outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def reauthorize_connector(self, request: outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def activate_connector(self, request: outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def deactivate_connector(self, request: outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def verify_connector(self, request: outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ConnectorServiceASGIApplication(ConnectASGIApplication[ConnectorService]):
    def __init__(self, service: ConnectorService | AsyncGenerator[ConnectorService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/outbox.v1.ConnectorService/CreateConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_connector,
                ),
                "/outbox.v1.ConnectorService/CreateManagedConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateManagedConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest,
                        output=google_dot_longrunning_dot_operations__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_managed_connector,
                ),
                "/outbox.v1.ConnectorService/GetConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="GetConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.GetConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.GetConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_connector,
                ),
                "/outbox.v1.ConnectorService/ListConnectors": Endpoint.unary(
                    method=MethodInfo(
                        name="ListConnectors",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest,
                        output=outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_connectors,
                ),
                "/outbox.v1.ConnectorService/UpdateConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_connector,
                ),
                "/outbox.v1.ConnectorService/DeleteConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_connector,
                ),
                "/outbox.v1.ConnectorService/DetachProvisionedResource": Endpoint.unary(
                    method=MethodInfo(
                        name="DetachProvisionedResource",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest,
                        output=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.detach_provisioned_resource,
                ),
                "/outbox.v1.ConnectorService/ReauthorizeConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="ReauthorizeConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.reauthorize_connector,
                ),
                "/outbox.v1.ConnectorService/ActivateConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="ActivateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.activate_connector,
                ),
                "/outbox.v1.ConnectorService/DeactivateConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="DeactivateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.deactivate_connector,
                ),
                "/outbox.v1.ConnectorService/VerifyConnector": Endpoint.unary(
                    method=MethodInfo(
                        name="VerifyConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.verify_connector,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.ConnectorService"


class ConnectorServiceClient(ConnectClient):
    async def create_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_managed_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.Operation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateManagedConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest,
                output=google_dot_longrunning_dot_operations__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.GetConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.GetConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.GetConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.GetConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_connectors(
        self,
        request: outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListConnectors",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest,
                output=outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def detach_provisioned_resource(
        self,
        request: outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DetachProvisionedResource",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest,
                output=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def reauthorize_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReauthorizeConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def activate_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ActivateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def deactivate_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeactivateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def verify_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VerifyConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ConnectorServiceSync(Protocol):
    def create_connector(self, request: outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_managed_connector(self, request: outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_connector(self, request: outbox_dot_v1_dot_connector__pb2.GetConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.GetConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_connectors(self, request: outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_connector(self, request: outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_connector(self, request: outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def detach_provisioned_resource(self, request: outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def reauthorize_connector(self, request: outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def activate_connector(self, request: outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def deactivate_connector(self, request: outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def verify_connector(self, request: outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ConnectorServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ConnectorServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/outbox.v1.ConnectorService/CreateConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_connector,
                ),
                "/outbox.v1.ConnectorService/CreateManagedConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateManagedConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest,
                        output=google_dot_longrunning_dot_operations__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_managed_connector,
                ),
                "/outbox.v1.ConnectorService/GetConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.GetConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.GetConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_connector,
                ),
                "/outbox.v1.ConnectorService/ListConnectors": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListConnectors",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest,
                        output=outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_connectors,
                ),
                "/outbox.v1.ConnectorService/UpdateConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_connector,
                ),
                "/outbox.v1.ConnectorService/DeleteConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_connector,
                ),
                "/outbox.v1.ConnectorService/DetachProvisionedResource": EndpointSync.unary(
                    method=MethodInfo(
                        name="DetachProvisionedResource",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest,
                        output=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.detach_provisioned_resource,
                ),
                "/outbox.v1.ConnectorService/ReauthorizeConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReauthorizeConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.reauthorize_connector,
                ),
                "/outbox.v1.ConnectorService/ActivateConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="ActivateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.activate_connector,
                ),
                "/outbox.v1.ConnectorService/DeactivateConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeactivateConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.deactivate_connector,
                ),
                "/outbox.v1.ConnectorService/VerifyConnector": EndpointSync.unary(
                    method=MethodInfo(
                        name="VerifyConnector",
                        service_name="outbox.v1.ConnectorService",
                        input=outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest,
                        output=outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.verify_connector,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.ConnectorService"


class ConnectorServiceClientSync(ConnectClientSync):
    def create_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.CreateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.CreateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_managed_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.Operation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateManagedConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.CreateManagedConnectorRequest,
                output=google_dot_longrunning_dot_operations__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.GetConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.GetConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.GetConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.GetConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_connectors(
        self,
        request: outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListConnectors",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.ListConnectorsRequest,
                output=outbox_dot_v1_dot_connector__pb2.ListConnectorsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.UpdateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.UpdateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.DeleteConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.DeleteConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def detach_provisioned_resource(
        self,
        request: outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DetachProvisionedResource",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceRequest,
                output=outbox_dot_v1_dot_connector__pb2.DetachProvisionedResourceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def reauthorize_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReauthorizeConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.ReauthorizeConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def activate_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ActivateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.ActivateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.ActivateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def deactivate_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeactivateConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.DeactivateConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def verify_connector(
        self,
        request: outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VerifyConnector",
                service_name="outbox.v1.ConnectorService",
                input=outbox_dot_v1_dot_connector__pb2.VerifyConnectorRequest,
                output=outbox_dot_v1_dot_connector__pb2.VerifyConnectorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
