# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: outbox/v1/destination.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import outbox.v1.destination_pb2 as outbox_dot_v1_dot_destination__pb2


class DestinationService(Protocol):
    async def create_destination(self, request: outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_destination(self, request: outbox_dot_v1_dot_destination__pb2.GetDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.GetDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_destinations(self, request: outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_destination(self, request: outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_destination(self, request: outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def test_destination(self, request: outbox_dot_v1_dot_destination__pb2.TestDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.TestDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_destination_test_results(self, request: outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def validate_destination_filter(self, request: outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def poll_events(self, request: outbox_dot_v1_dot_destination__pb2.PollEventsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.PollEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DestinationServiceASGIApplication(ConnectASGIApplication[DestinationService]):
    def __init__(self, service: DestinationService | AsyncGenerator[DestinationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/outbox.v1.DestinationService/CreateDestination": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_destination,
                ),
                "/outbox.v1.DestinationService/GetDestination": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.GetDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.GetDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_destination,
                ),
                "/outbox.v1.DestinationService/ListDestinations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDestinations",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest,
                        output=outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_destinations,
                ),
                "/outbox.v1.DestinationService/UpdateDestination": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_destination,
                ),
                "/outbox.v1.DestinationService/DeleteDestination": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_destination,
                ),
                "/outbox.v1.DestinationService/TestDestination": Endpoint.unary(
                    method=MethodInfo(
                        name="TestDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.TestDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.TestDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.test_destination,
                ),
                "/outbox.v1.DestinationService/ListDestinationTestResults": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDestinationTestResults",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest,
                        output=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_destination_test_results,
                ),
                "/outbox.v1.DestinationService/ValidateDestinationFilter": Endpoint.unary(
                    method=MethodInfo(
                        name="ValidateDestinationFilter",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest,
                        output=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.validate_destination_filter,
                ),
                "/outbox.v1.DestinationService/PollEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="PollEvents",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.PollEventsRequest,
                        output=outbox_dot_v1_dot_destination__pb2.PollEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.poll_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.DestinationService"


class DestinationServiceClient(ConnectClient):
    async def create_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.GetDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.GetDestinationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.GetDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.GetDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_destinations(
        self,
        request: outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDestinations",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest,
                output=outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def test_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.TestDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.TestDestinationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TestDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.TestDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.TestDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_destination_test_results(
        self,
        request: outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDestinationTestResults",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest,
                output=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def validate_destination_filter(
        self,
        request: outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateDestinationFilter",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest,
                output=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def poll_events(
        self,
        request: outbox_dot_v1_dot_destination__pb2.PollEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.PollEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PollEvents",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.PollEventsRequest,
                output=outbox_dot_v1_dot_destination__pb2.PollEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class DestinationServiceSync(Protocol):
    def create_destination(self, request: outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_destination(self, request: outbox_dot_v1_dot_destination__pb2.GetDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.GetDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_destinations(self, request: outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_destination(self, request: outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_destination(self, request: outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def test_destination(self, request: outbox_dot_v1_dot_destination__pb2.TestDestinationRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.TestDestinationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_destination_test_results(self, request: outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def validate_destination_filter(self, request: outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def poll_events(self, request: outbox_dot_v1_dot_destination__pb2.PollEventsRequest, ctx: RequestContext) -> outbox_dot_v1_dot_destination__pb2.PollEventsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DestinationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: DestinationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/outbox.v1.DestinationService/CreateDestination": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_destination,
                ),
                "/outbox.v1.DestinationService/GetDestination": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.GetDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.GetDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_destination,
                ),
                "/outbox.v1.DestinationService/ListDestinations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDestinations",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest,
                        output=outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_destinations,
                ),
                "/outbox.v1.DestinationService/UpdateDestination": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_destination,
                ),
                "/outbox.v1.DestinationService/DeleteDestination": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_destination,
                ),
                "/outbox.v1.DestinationService/TestDestination": EndpointSync.unary(
                    method=MethodInfo(
                        name="TestDestination",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.TestDestinationRequest,
                        output=outbox_dot_v1_dot_destination__pb2.TestDestinationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.test_destination,
                ),
                "/outbox.v1.DestinationService/ListDestinationTestResults": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDestinationTestResults",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest,
                        output=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_destination_test_results,
                ),
                "/outbox.v1.DestinationService/ValidateDestinationFilter": EndpointSync.unary(
                    method=MethodInfo(
                        name="ValidateDestinationFilter",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest,
                        output=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.validate_destination_filter,
                ),
                "/outbox.v1.DestinationService/PollEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="PollEvents",
                        service_name="outbox.v1.DestinationService",
                        input=outbox_dot_v1_dot_destination__pb2.PollEventsRequest,
                        output=outbox_dot_v1_dot_destination__pb2.PollEventsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.poll_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.DestinationService"


class DestinationServiceClientSync(ConnectClientSync):
    def create_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.CreateDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.CreateDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.GetDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.GetDestinationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.GetDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.GetDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_destinations(
        self,
        request: outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDestinations",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.ListDestinationsRequest,
                output=outbox_dot_v1_dot_destination__pb2.ListDestinationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.UpdateDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.UpdateDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.DeleteDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.DeleteDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def test_destination(
        self,
        request: outbox_dot_v1_dot_destination__pb2.TestDestinationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.TestDestinationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TestDestination",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.TestDestinationRequest,
                output=outbox_dot_v1_dot_destination__pb2.TestDestinationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_destination_test_results(
        self,
        request: outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDestinationTestResults",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsRequest,
                output=outbox_dot_v1_dot_destination__pb2.ListDestinationTestResultsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def validate_destination_filter(
        self,
        request: outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateDestinationFilter",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterRequest,
                output=outbox_dot_v1_dot_destination__pb2.ValidateDestinationFilterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def poll_events(
        self,
        request: outbox_dot_v1_dot_destination__pb2.PollEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_destination__pb2.PollEventsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PollEvents",
                service_name="outbox.v1.DestinationService",
                input=outbox_dot_v1_dot_destination__pb2.PollEventsRequest,
                output=outbox_dot_v1_dot_destination__pb2.PollEventsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
