# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: outbox/v1/message.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import outbox.v1.message_pb2 as outbox_dot_v1_dot_message__pb2


class MessageService(Protocol):
    async def create_message(self, request: outbox_dot_v1_dot_message__pb2.CreateMessageRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.CreateMessageResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_message(self, request: outbox_dot_v1_dot_message__pb2.UpdateMessageRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.UpdateMessageResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_message(self, request: outbox_dot_v1_dot_message__pb2.DeleteMessageRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.DeleteMessageResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_messages(self, request: outbox_dot_v1_dot_message__pb2.ListMessagesRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.ListMessagesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def send_read_receipt(self, request: outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def send_typing_indicator(self, request: outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MessageServiceASGIApplication(ConnectASGIApplication[MessageService]):
    def __init__(self, service: MessageService | AsyncGenerator[MessageService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/outbox.v1.MessageService/CreateMessage": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateMessage",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.CreateMessageRequest,
                        output=outbox_dot_v1_dot_message__pb2.CreateMessageResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_message,
                ),
                "/outbox.v1.MessageService/UpdateMessage": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateMessage",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.UpdateMessageRequest,
                        output=outbox_dot_v1_dot_message__pb2.UpdateMessageResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_message,
                ),
                "/outbox.v1.MessageService/DeleteMessage": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteMessage",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.DeleteMessageRequest,
                        output=outbox_dot_v1_dot_message__pb2.DeleteMessageResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_message,
                ),
                "/outbox.v1.MessageService/ListMessages": Endpoint.unary(
                    method=MethodInfo(
                        name="ListMessages",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.ListMessagesRequest,
                        output=outbox_dot_v1_dot_message__pb2.ListMessagesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_messages,
                ),
                "/outbox.v1.MessageService/SendReadReceipt": Endpoint.unary(
                    method=MethodInfo(
                        name="SendReadReceipt",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest,
                        output=outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.send_read_receipt,
                ),
                "/outbox.v1.MessageService/SendTypingIndicator": Endpoint.unary(
                    method=MethodInfo(
                        name="SendTypingIndicator",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest,
                        output=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.send_typing_indicator,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.MessageService"


class MessageServiceClient(ConnectClient):
    async def create_message(
        self,
        request: outbox_dot_v1_dot_message__pb2.CreateMessageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.CreateMessageResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateMessage",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.CreateMessageRequest,
                output=outbox_dot_v1_dot_message__pb2.CreateMessageResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_message(
        self,
        request: outbox_dot_v1_dot_message__pb2.UpdateMessageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.UpdateMessageResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateMessage",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.UpdateMessageRequest,
                output=outbox_dot_v1_dot_message__pb2.UpdateMessageResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_message(
        self,
        request: outbox_dot_v1_dot_message__pb2.DeleteMessageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.DeleteMessageResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteMessage",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.DeleteMessageRequest,
                output=outbox_dot_v1_dot_message__pb2.DeleteMessageResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_messages(
        self,
        request: outbox_dot_v1_dot_message__pb2.ListMessagesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.ListMessagesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMessages",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.ListMessagesRequest,
                output=outbox_dot_v1_dot_message__pb2.ListMessagesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def send_read_receipt(
        self,
        request: outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendReadReceipt",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest,
                output=outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def send_typing_indicator(
        self,
        request: outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendTypingIndicator",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest,
                output=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class MessageServiceSync(Protocol):
    def create_message(self, request: outbox_dot_v1_dot_message__pb2.CreateMessageRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.CreateMessageResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_message(self, request: outbox_dot_v1_dot_message__pb2.UpdateMessageRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.UpdateMessageResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_message(self, request: outbox_dot_v1_dot_message__pb2.DeleteMessageRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.DeleteMessageResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_messages(self, request: outbox_dot_v1_dot_message__pb2.ListMessagesRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.ListMessagesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def send_read_receipt(self, request: outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def send_typing_indicator(self, request: outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest, ctx: RequestContext) -> outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class MessageServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: MessageServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/outbox.v1.MessageService/CreateMessage": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateMessage",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.CreateMessageRequest,
                        output=outbox_dot_v1_dot_message__pb2.CreateMessageResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_message,
                ),
                "/outbox.v1.MessageService/UpdateMessage": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateMessage",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.UpdateMessageRequest,
                        output=outbox_dot_v1_dot_message__pb2.UpdateMessageResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_message,
                ),
                "/outbox.v1.MessageService/DeleteMessage": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteMessage",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.DeleteMessageRequest,
                        output=outbox_dot_v1_dot_message__pb2.DeleteMessageResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_message,
                ),
                "/outbox.v1.MessageService/ListMessages": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListMessages",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.ListMessagesRequest,
                        output=outbox_dot_v1_dot_message__pb2.ListMessagesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_messages,
                ),
                "/outbox.v1.MessageService/SendReadReceipt": EndpointSync.unary(
                    method=MethodInfo(
                        name="SendReadReceipt",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest,
                        output=outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.send_read_receipt,
                ),
                "/outbox.v1.MessageService/SendTypingIndicator": EndpointSync.unary(
                    method=MethodInfo(
                        name="SendTypingIndicator",
                        service_name="outbox.v1.MessageService",
                        input=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest,
                        output=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.send_typing_indicator,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.MessageService"


class MessageServiceClientSync(ConnectClientSync):
    def create_message(
        self,
        request: outbox_dot_v1_dot_message__pb2.CreateMessageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.CreateMessageResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateMessage",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.CreateMessageRequest,
                output=outbox_dot_v1_dot_message__pb2.CreateMessageResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_message(
        self,
        request: outbox_dot_v1_dot_message__pb2.UpdateMessageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.UpdateMessageResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateMessage",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.UpdateMessageRequest,
                output=outbox_dot_v1_dot_message__pb2.UpdateMessageResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_message(
        self,
        request: outbox_dot_v1_dot_message__pb2.DeleteMessageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.DeleteMessageResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteMessage",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.DeleteMessageRequest,
                output=outbox_dot_v1_dot_message__pb2.DeleteMessageResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_messages(
        self,
        request: outbox_dot_v1_dot_message__pb2.ListMessagesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.ListMessagesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMessages",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.ListMessagesRequest,
                output=outbox_dot_v1_dot_message__pb2.ListMessagesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def send_read_receipt(
        self,
        request: outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendReadReceipt",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.SendReadReceiptRequest,
                output=outbox_dot_v1_dot_message__pb2.SendReadReceiptResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def send_typing_indicator(
        self,
        request: outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendTypingIndicator",
                service_name="outbox.v1.MessageService",
                input=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorRequest,
                output=outbox_dot_v1_dot_message__pb2.SendTypingIndicatorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
