# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: outbox/v1/template.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import outbox.v1.template_pb2 as outbox_dot_v1_dot_template__pb2


class TemplateService(Protocol):
    async def create_template(self, request: outbox_dot_v1_dot_template__pb2.CreateTemplateRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.CreateTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_template(self, request: outbox_dot_v1_dot_template__pb2.GetTemplateRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.GetTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_templates(self, request: outbox_dot_v1_dot_template__pb2.ListTemplatesRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.ListTemplatesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_template(self, request: outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TemplateServiceASGIApplication(ConnectASGIApplication[TemplateService]):
    def __init__(self, service: TemplateService | AsyncGenerator[TemplateService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/outbox.v1.TemplateService/CreateTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateTemplate",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.CreateTemplateRequest,
                        output=outbox_dot_v1_dot_template__pb2.CreateTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_template,
                ),
                "/outbox.v1.TemplateService/GetTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTemplate",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.GetTemplateRequest,
                        output=outbox_dot_v1_dot_template__pb2.GetTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_template,
                ),
                "/outbox.v1.TemplateService/ListTemplates": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTemplates",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.ListTemplatesRequest,
                        output=outbox_dot_v1_dot_template__pb2.ListTemplatesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_templates,
                ),
                "/outbox.v1.TemplateService/DeleteTemplate": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteTemplate",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest,
                        output=outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_template,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.TemplateService"


class TemplateServiceClient(ConnectClient):
    async def create_template(
        self,
        request: outbox_dot_v1_dot_template__pb2.CreateTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.CreateTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateTemplate",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.CreateTemplateRequest,
                output=outbox_dot_v1_dot_template__pb2.CreateTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_template(
        self,
        request: outbox_dot_v1_dot_template__pb2.GetTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.GetTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTemplate",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.GetTemplateRequest,
                output=outbox_dot_v1_dot_template__pb2.GetTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_templates(
        self,
        request: outbox_dot_v1_dot_template__pb2.ListTemplatesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.ListTemplatesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTemplates",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.ListTemplatesRequest,
                output=outbox_dot_v1_dot_template__pb2.ListTemplatesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_template(
        self,
        request: outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTemplate",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest,
                output=outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class TemplateServiceSync(Protocol):
    def create_template(self, request: outbox_dot_v1_dot_template__pb2.CreateTemplateRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.CreateTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_template(self, request: outbox_dot_v1_dot_template__pb2.GetTemplateRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.GetTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_templates(self, request: outbox_dot_v1_dot_template__pb2.ListTemplatesRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.ListTemplatesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_template(self, request: outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest, ctx: RequestContext) -> outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TemplateServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: TemplateServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/outbox.v1.TemplateService/CreateTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateTemplate",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.CreateTemplateRequest,
                        output=outbox_dot_v1_dot_template__pb2.CreateTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_template,
                ),
                "/outbox.v1.TemplateService/GetTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTemplate",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.GetTemplateRequest,
                        output=outbox_dot_v1_dot_template__pb2.GetTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_template,
                ),
                "/outbox.v1.TemplateService/ListTemplates": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTemplates",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.ListTemplatesRequest,
                        output=outbox_dot_v1_dot_template__pb2.ListTemplatesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_templates,
                ),
                "/outbox.v1.TemplateService/DeleteTemplate": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteTemplate",
                        service_name="outbox.v1.TemplateService",
                        input=outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest,
                        output=outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_template,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/outbox.v1.TemplateService"


class TemplateServiceClientSync(ConnectClientSync):
    def create_template(
        self,
        request: outbox_dot_v1_dot_template__pb2.CreateTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.CreateTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateTemplate",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.CreateTemplateRequest,
                output=outbox_dot_v1_dot_template__pb2.CreateTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_template(
        self,
        request: outbox_dot_v1_dot_template__pb2.GetTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.GetTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTemplate",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.GetTemplateRequest,
                output=outbox_dot_v1_dot_template__pb2.GetTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_templates(
        self,
        request: outbox_dot_v1_dot_template__pb2.ListTemplatesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.ListTemplatesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTemplates",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.ListTemplatesRequest,
                output=outbox_dot_v1_dot_template__pb2.ListTemplatesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_template(
        self,
        request: outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTemplate",
                service_name="outbox.v1.TemplateService",
                input=outbox_dot_v1_dot_template__pb2.DeleteTemplateRequest,
                output=outbox_dot_v1_dot_template__pb2.DeleteTemplateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
