# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: google/longrunning/operations.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.longrunning.operations_pb2 as google_dot_longrunning_dot_operations__pb2
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2


class Operations(Protocol):
    async def list_operations(self, request: google_dot_longrunning_dot_operations__pb2.ListOperationsRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.ListOperationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_operation(self, request: google_dot_longrunning_dot_operations__pb2.GetOperationRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_operation(self, request: google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def cancel_operation(self, request: google_dot_longrunning_dot_operations__pb2.CancelOperationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def wait_operation(self, request: google_dot_longrunning_dot_operations__pb2.WaitOperationRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class OperationsASGIApplication(ConnectASGIApplication[Operations]):
    def __init__(self, service: Operations | AsyncGenerator[Operations], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/google.longrunning.Operations/ListOperations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListOperations",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.ListOperationsRequest,
                        output=google_dot_longrunning_dot_operations__pb2.ListOperationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_operations,
                ),
                "/google.longrunning.Operations/GetOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.GetOperationRequest,
                        output=google_dot_longrunning_dot_operations__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_operation,
                ),
                "/google.longrunning.Operations/DeleteOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_operation,
                ),
                "/google.longrunning.Operations/CancelOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.CancelOperationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cancel_operation,
                ),
                "/google.longrunning.Operations/WaitOperation": Endpoint.unary(
                    method=MethodInfo(
                        name="WaitOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.WaitOperationRequest,
                        output=google_dot_longrunning_dot_operations__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.wait_operation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/google.longrunning.Operations"


class OperationsClient(ConnectClient):
    async def list_operations(
        self,
        request: google_dot_longrunning_dot_operations__pb2.ListOperationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.ListOperationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListOperations",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.ListOperationsRequest,
                output=google_dot_longrunning_dot_operations__pb2.ListOperationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.GetOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.Operation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.GetOperationRequest,
                output=google_dot_longrunning_dot_operations__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.CancelOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.CancelOperationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def wait_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.WaitOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.Operation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="WaitOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.WaitOperationRequest,
                output=google_dot_longrunning_dot_operations__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class OperationsSync(Protocol):
    def list_operations(self, request: google_dot_longrunning_dot_operations__pb2.ListOperationsRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.ListOperationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_operation(self, request: google_dot_longrunning_dot_operations__pb2.GetOperationRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_operation(self, request: google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def cancel_operation(self, request: google_dot_longrunning_dot_operations__pb2.CancelOperationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def wait_operation(self, request: google_dot_longrunning_dot_operations__pb2.WaitOperationRequest, ctx: RequestContext) -> google_dot_longrunning_dot_operations__pb2.Operation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class OperationsWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: OperationsSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/google.longrunning.Operations/ListOperations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListOperations",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.ListOperationsRequest,
                        output=google_dot_longrunning_dot_operations__pb2.ListOperationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_operations,
                ),
                "/google.longrunning.Operations/GetOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.GetOperationRequest,
                        output=google_dot_longrunning_dot_operations__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_operation,
                ),
                "/google.longrunning.Operations/DeleteOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_operation,
                ),
                "/google.longrunning.Operations/CancelOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.CancelOperationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cancel_operation,
                ),
                "/google.longrunning.Operations/WaitOperation": EndpointSync.unary(
                    method=MethodInfo(
                        name="WaitOperation",
                        service_name="google.longrunning.Operations",
                        input=google_dot_longrunning_dot_operations__pb2.WaitOperationRequest,
                        output=google_dot_longrunning_dot_operations__pb2.Operation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.wait_operation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/google.longrunning.Operations"


class OperationsClientSync(ConnectClientSync):
    def list_operations(
        self,
        request: google_dot_longrunning_dot_operations__pb2.ListOperationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.ListOperationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListOperations",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.ListOperationsRequest,
                output=google_dot_longrunning_dot_operations__pb2.ListOperationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.GetOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.Operation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.GetOperationRequest,
                output=google_dot_longrunning_dot_operations__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.DeleteOperationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def cancel_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.CancelOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.CancelOperationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def wait_operation(
        self,
        request: google_dot_longrunning_dot_operations__pb2.WaitOperationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_longrunning_dot_operations__pb2.Operation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="WaitOperation",
                service_name="google.longrunning.Operations",
                input=google_dot_longrunning_dot_operations__pb2.WaitOperationRequest,
                output=google_dot_longrunning_dot_operations__pb2.Operation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
